### ISSUE TITLE
Can add __init__.py to be a module ?

### ISSUE THREAD

**Issue by MY0613** [jruere/multiprocessing-logging#11]
Hi, 
Why not to add __init__.py lets multiprocessing-logging to be a module?
Thanks.

**Comment by jruere** [comment]
`multiprocessing-logging` _is_ a module. Since there's no need for sub-modules, there's no need to change it into a directory+`__init__.py` module.

Which functionality are you missing?

**Comment by MY0613** [comment]
Just want to use it as sub-module, more structured in application developing.
This is not necessary and just to share thoughts.
Thanks for reply.

**Comment by jruere** [comment]
Install it as a dependency. No need to copy it into your project.

Even if you want to change it, fork the project and install from there.

**Comment by jruere** [comment]
I'll close as I see no point in doing this.
