### ISSUE TITLE
Queue Handler

### ISSUE THREAD

**Issue by zauddelig** [jruere/multiprocessing-logging#15]
why don't you use `logging.handlers.QueueHandler`?

**Comment by jruere** [comment]
I was not aware of that module. Thank you for pointing it out. 

At first glance, the only reason to use this is for Python 2.7.

I'll play a bit with that module and add a note in the readme. 
Maybe a deprecation warning for Python 3.

**Comment by jruere** [comment]
@zauddelig I now understand your question differently. Now I understand you ask why the QueueHandler in the stdlib is not used by multiprocessing-logging.
The answer is that 2.7 is supported.

After reading a bit more on QueueHandler/Listener, I see it's very manual to make them work.
Perhaps when 2.7 is deprecated, I could consider this module just becoming a configuration helper for the stdlib. For now, I don't see anything that could be done.

If I misunderstood your point, please re-open.
