### ISSUE TITLE
feature request: uninstall_mp_handler()

### ISSUE THREAD

**Issue by codekiln** [jruere/multiprocessing-logging#17]
It's common to have a parent process initiate multiprocessing and then still perform logging afterwards. I'd like to request an `uninstall_mp_handler()` function that would be the mirror of `install_mp_handler()`, so the parent process could continue after the completion of multiprocessing jobs without the overhead of a synchronized queue.

**Comment by jruere** [comment]
OK, I'll take a look when I have time. You can also send a PR. ;)

**Comment by jruere** [comment]
A PR was merged.
