### ISSUE TITLE
Lost LogRecords

### ISSUE THREAD

**Issue by RatkoJ** [jruere/multiprocessing-logging#18]
Hi,

I've come across a situation where logs are randomly lost and I cannot figure out why. Not sure if this is timing related (I added a sleep to see if it makes a difference...no). 

In my project I normally do `logger = logging.getLogger("someName")` which I then use throughout the file. So I was playing with a small example when I noticed that logs go missing quite often. Sometimes just the first message prints, sometimes more, sometimes all. If I comment out the install_mp_handler(), it seems to work properly every time. My project is using multiprocessing, but this example is just a single file for testing.

My setup:
python3.6.2
MacOS Mojave 10.14

Here's the code and the output from a few consecutive runs:
```python
import logging, time, multiprocessing_logging

logger = logging.getLogger("mymodule")

def logSomething():
    logger.debug("Debug message")
    logger.info("Info message")
    logger.warning("Warning message")
    logger.error("Error message")

if __name__=="__main__":
    logging.basicConfig(level=logging.DEBUG)
    multiprocessing_logging.install_mp_handler()
    time.sleep(2)  # to give the threads time to start properly
    logSomething()
```

Output:
```
~/dev/test > python3 testLogging.py 
DEBUG:mymodule:Debug message
INFO:mymodule:Info message
WARNING:mymodule:Warning message

~/dev/test > python3 testLogging.py 
DEBUG:mymodule:Debug message
INFO:mymodule:Info message

~/dev/test > python3 testLogging.py 
DEBUG:mymodule:Debug message
INFO:mymodule:Info message

~/dev/test > python3 testLogging.py 
DEBUG:mymodule:Debug message
INFO:mymodule:Info message

~/dev/test > python3 testLogging.py 
DEBUG:mymodule:Debug message
INFO:mymodule:Info message
WARNING:mymodule:Warning message
ERROR:mymodule:Error message
```

**Comment by oPromessa** [comment]
Hmmm... you know this smallest is not actually performing any multi-processing logging.

Anyhow, I've ran your sample code under:
* Mac OS 10.13.6 High Sierra + python 2.7.10
* Ubuntu 17.10 (GNU/Linux 4.13.0-43-generic x86_64) + python 3.6.3

...and no issues... but it's not your specific setup. Sorry!
```bash
$  while true; do python LogRecords.py ; sleep 5; echo  ---------; done
DEBUG:mymodule:Debug message
INFO:mymodule:Info message
WARNING:mymodule:Warning message
ERROR:mymodule:Error message
---------
DEBUG:mymodule:Debug message
INFO:mymodule:Info message
WARNING:mymodule:Warning message
ERROR:mymodule:Error message
---------
DEBUG:mymodule:Debug message
INFO:mymodule:Info message
WARNING:mymodule:Warning message
ERROR:mymodule:Error message
```

**Comment by oPromessa** [comment]
One thing I don't like in the code is that you define `logger = logging.getLogger("mymodule")`prior to issuing `logging.basicConfig(level=logging.DEBUG)`.

Can you also try your code **without** calling `multiprocessing_logging.install_mp_handler()` on python 3.6.2 just to confirm if this is related with the multiprocessing_logging lib or not.

Finally...if it works under python 3.7...maybe upgrade to it!

**Comment by RatkoJ** [comment]
> One thing I don't like in the code is that you define `logger = logging.getLogger("mymodule")`prior to issuing `logging.basicConfig(level=logging.DEBUG)`.
Yeah, it thought it's weird too, but it makes no difference if I call it right before issuing the log commands.

> Can you also try your code **without** calling `multiprocessing_logging.install_mp_handler()` on python 3.6.2 just to confirm if this is related with the multiprocessing_logging lib or not.
Without the install_mp_handler it works fine. 
It just seems like something gets lost during the switchover of the handlers... 

> Finally...if it works under python 3.7...maybe upgrade to it!
Yeah, I reinstalled all my other packages and it seems to work... but I will need more testing to see if something else broke...

**Comment by RatkoJ** [comment]
I think I figured it out... The problem is that `MultiProcessingHandler.close()` gets called before the queue is empty. The way close() is structured, it sets the `_is_closed` flag BEFORE it joins the thread so the while loop exits immediately. So the timeout on the join doesn't serve the intended purpose here.

Instead I think what should happen is set the flag AFTER the join with the timeout:
```python
if not self._is_closed:
            self._receive_thread.join(5.0)  # Waits for receive queue to empty.
            self._is_closed = True
```

I can submit a pull request if you think this makes sense and won't break something else.

**Comment by oPromessa** [comment]
I’m, like you, a user of this repository and not the owner. 

Also. It could be useful to have additional logging from this lib itself. I think the following command does that. 

multiprocessing.log_to_stderr()



Maybe not related but I have to run the following function at the end of my apps prior to exiting to allow proper closing of logs. 

 # -----------------------------------------------------------------------------
# logging_close_handlers
#
# Close logging handlers
#
def logging_close_handlers():
    """ logging_close_handlers

    Close logging handlers

    """
    handlers = logging.getLogger().handlers[:]
    for handler in handlers:
        handler.close()
        logging.getLogger().removeHandler(handler)

**Comment by oPromessa** [comment]
> ```python
> if not self._is_closed:
>             self._receive_thread.join(5.0)  # Waits for receive queue to empty.
>             self._is_closed = True
> ```
> 
> I can submit a pull request if you think this makes sense and won't break something else.

I took a second look at your code change and I see your point. 👍 
But then, the while loop is protected with queue.empty() so the `_receive` thread should still emit the logging messages in queue even after close, no? At least within the 5.0 seconds timeout of the `_receive_thread_join(5.0)`:
```python
while not (self._is_closed and self.queue.empty()):`
```

With your code change you allow 5 seconds for the receive thread to finalise it's work. 
* If queue is large enough queue we may still loose messages.
* But then again, that is the case with the original code also.
(sorry for the rambling)

So I guess if it solved your particular problem the change does not seem to hurt as the behaviour seems to me would be the same. 
* Just don't know why in some situations in your system the problem occurred in the first place.

**Comment by RatkoJ** [comment]
> But then, the while loop is protected with queue.empty() so the _receive thread should still emit the logging messages in queue even after close, no?

Yes you are correct. So this must be a timing problem. At the time when setting `_is_closed=True`, the queue is still empty, presumably because the last log messages haven't "arrived" yet on the receiving end. 

Actually now I don't think my fix is a proper fix. I think the original order of `_is_close` and `join()` is correct because setting `_is_close=True` is the signal to terminate and then we wait for that termination to happen gracefully with the `join()`. In my fix we run the risk of the main program terminating before the Thread and therefore the Thread gets killed forcefully and there are uncleaned up resources.  

> Just don't know why in some situations in your system the problem occurred in the first place.
Yeah, no idea... the problem is quite weird.

**Comment by jruere** [comment]
Sorry for the delay.

Fundamentally, since processes are independent and the main process could decide to stop before its children, the children could continue to send messages.

Although a 1s sleep would help 99.9999% of the time in your particular example, it will not help in other cases when the children keep sending messages. So, in general, there's not solution to "not losing any records" other than preventing the main process from terminating until all children close their end of the queue.

This is out of scope though. :)

**Comment by RatkoJ** [comment]
Actually, if you look at my original sample code, it doesn't use any multiprocessing or threading and yet the messages get lost. So it means that the cleanup method between the receiver thread and the listener wasn't working as expected. As far as I remember (it's been a while), I traced it down to the `self.queue.empty()` returning True when in fact it wasn't, as mentioned in one of the comments above.

In any case, after spending a lot of time trying to fix this and realizing that this is a lot more complicated than it seems on the surface, I switched to using QueueHandler/Listener.

**Comment by jruere** [comment]
Even though your example does not use a separate process, the Queue it uses is a multiprocessing queue so when you send a message, it will arrive after a while as it leaves the process.

With QueueHandler/Listener are you using threads or processes?
If you are using processes, it should have the same behavior as this module.

Just for my curiosity, could you post how you setup QueueHandler/Listener?

**Comment by RatkoJ** [comment]
Here's the code. I ripped it out of the bigger logging module that I am using with various handlers, formatters etc so it looks a bit ugly this way. In my application, throughout the execution, I start up and shutdown multiple worker processes (not threads) that need logging output. The shutting down of worker processes was also causing deadlocks for two possible reasons: 

1. if logging right before spawning the processes, sometimes the already locked Queue was being passed to the processes... which the process couldn't release then
2. if a process is being joined() but the Queue isn't empty yet, it can deadlock. The solutions are either don't join(), clean up the queue (but if Queue.empty reports incorrectly you're out of luck) or use cancel_join_thread (which could lead to lost data).

In any case, I spent a lot of time trying to fix it so it works on my system, but without success and I don't remember why anymore. I'm sorry I couldn't post any pull requests with improvements but I am at least trying to share some things I've learned. I also have some links saved that describe these issues if you are interested.

```python
import multiprocessing, logging, sys
from logging.handlers import QueueHandler, QueueListener

logQueue = multiprocessing.Queue(-1)
logQueue.cancel_join_thread()
qListener = None

def initLogging(level=logging.DEBUG):
    handlers = []

    global logQueue, qListener
    stdoutHandler = logging.StreamHandler(sys.stdout)
    stdoutHandler.setLevel(level)
    handlers.append(stdoutHandler)

    # we don't want any level filtering here
    qHandler = QueueHandler(logQueue)
    qHandler.setLevel(logging.DEBUG)

    # set up the root logger with the QueueHandler
    rootLogger = logging.getLogger()
    rootLogger.addHandler(qHandler)
    rootLogger.setLevel(level)

    # this will receive all the logs from the processes through a Queue
    # and distribute them to the individual handlers as set up above
    qListener = QueueListener(logQueue, *handlers, respect_handler_level=True)
    qListener.start()

def stopLogging():
    qListener.stop()

def logSomething():
    logger.debug("Debug message")
    logger.info("Info message")
    logger.warning("Warning message")
    logger.error("Error message")

if __name__=="__main__":
    initLogging(logging.DEBUG)
    logger = logging.getLogger("example")
    logSomething()
    stopLogging()
```
