### ISSUE TITLE
function to automatically bootstrap

### ISSUE THREAD

**Issue by brianray** [jruere/multiprocessing-logging#2]
What about applying to all existing configured handlers?

perhaps something like this (untested)?

```python

    import multiprocessing_logging as mp_logging
    i = 0
    for x in list(logger.handlers):
        handler = mp_logging.MultiProcessingHandler('worker-logger-{}'.format(i),
                                                    sub_handler=x)
        logger.removeHandler(x)
        logger.addHandler(handler)
        i += 1
```

**Comment by jruere** [comment]
Nice idea!

Would you like to send a PR with that as a function in the multiprocessing_logging module and adding to the example in the README?

**Comment by jruere** [comment]
I finally got around to doing this. Please, let me know if it's good enough.

**Comment by brianray** [comment]
was it done here? https://github.com/jruere/multiprocessing-logging/commit/9d9bc6d9001debc1c040e8717888486e34fc175a

it would probably help you to use pull requests and associate with the issue.

Nonetheless LGTM :+1:

**Comment by jruere** [comment]
Great! Thanks for the idea.
