### ISSUE TITLE
self.queue.qsize() growing indefinitely

### ISSUE THREAD

**Issue by dfrank8** [jruere/multiprocessing-logging#20]
Not sure what is causing the problem, but randomly my sub_handler.emit() stops being called.

Also, I found that if I add print(self.queue.qsize()) in the emit() of MultiProcessingHandler, and I see qsize() start growing indefinitely right after my sub_handler's emit() is called for the last time.

Any idea what might be happening? I'd be happy to provide more detail if its deemed helpful. 

```
def emit(self, record):
    try:
          s = self._format_record(record)
          print(self.queue.qsize()) # grows indefinitely after sub_handler.emit() stops getting called
          self._send(s)
    except (KeyboardInterrupt, SystemExit):
          raise
    except:
          self.handleError(record)
```

**Comment by jruere** [comment]
No idea what could be happening. I never had this problem before.

Please post the version of all components.

**Comment by jruere** [comment]
Could you add a print after the call to watchtower emit in _receive? Maybe emit blocks forever.

Also before the thread is closed, just in case.

**Comment by dfrank8** [comment]
Reproduced with updated _receive() method:
```
def _receive(self):
    while not (self._is_closed and self.queue.empty()):
        try:
            record = self.queue.get(timeout=0.2)
            print("[MP] Calling emit() with queue " + str(self.queue))
            self.sub_handler.emit(record)
            print("[MP] After emit() with queue " + str(self.queue))
        except (KeyboardInterrupt, SystemExit):
            raise
        except EOFError:
            break
        except queue.Empty:
            pass  # This periodically checks if the logger is closed.
        except:
            traceback.print_exc(file=sys.stderr)
    print("[MP] Queue closing")
    self.queue.close()
    self.queue.join_thread()
```

console logs:
```
[MP] size: 0
[MP] size: 1
[MP] Calling emit() with queue <multiprocessing.queues.Queue object at 0x7fc768194ba8>
[WT] in emit()
[MP] After emit() with queue <multiprocessing.queues.Queue object at 0x7fc768194ba8>
[MP] Calling emit() with queue <multiprocessing.queues.Queue object at 0x7fc768194ba8>
[WT] in emit() < -- LAST TIME EMIT() IS CALLED
[MP] After emit() with queue <multiprocessing.queues.Queue object at 0x7fc768194ba8>
[MP] size: 0
[MP] size: 1
[MP] size: 2
[MP] size: 3
[MP] size: 4
[MP] size: 5
```
It does look like emit() is hanging since the "after emit()" is logged after the last call.

**Comment by dfrank8** [comment]
I agree with you that it doesn't seem like emit() is hanging. 

Unfortunately I have been unable to reproduce it on my local machine, and only see it in my production environment. For context: it only occurs in my worker tasks running django_rq, not sure if there is something in that library that is propagating this problem. I will continue to try to repro. 

Thank you!

**Comment by dfrank8** [comment]
@jruere I was able to circumvent the problem altogether, however I doubt I'll be the only person to experience this so I wanted to leave some details here.

I was using DjangoRQ, a redis-queue wrapper for asynchronous jobs, and it appears that they make use of os.fork() when they spawn. 

I was able to change my workers to use of SimpleWorker reference here which avoids os.fork():
https://github.com/rq/rq/blob/master/rq/worker.py#L921

Switching to that completely solved the problem. So there may be an issue with os.fork() somewhere, although this is unfortunately all the help I can provide. Thanks for the time!

Here's a great article demonstrating what I imagine is similar to this problem:
https://codewithoutrules.com/2018/09/04/python-multiprocessing/

**Comment by jruere** [comment]
Thanks for the additional information. I'll research a little and update the README if I find something.

**Comment by jruere** [comment]
I did not find anything more. `os.fork()` should work without problems, AFAICS.

**Comment by jruere** [comment]
I don't know what else to do here so I'll close it.
