### ISSUE TITLE
Why Pull Request #19 was discarded?

### ISSUE THREAD

**Issue by oPromessa** [jruere/multiprocessing-logging#21]
Hey @jruere , good job!

Just wondering why you did not merge PR #19 into your main line?

Thanks, oPromessa

**Comment by jruere** [comment]
I asked questions which were not answered for a long time. I thought you were no longer interested.

**Comment by oPromessa** [comment]
Sorry... I don't find where those questions are? I looked on the Pull Request itself but did not find them. Sorry! My mistake, maybe!

**Comment by jruere** [comment]
I made a comment in the pull request, which I reopened. Lets continue there.
Evidently, I'm not using the tool correctly.

**Comment by oPromessa** [comment]
Thank you! I **now** see your comments and I have answer them. Thanks for your support.
