### ISSUE TITLE
multiprocess_logger.py format error 

### ISSUE THREAD

**Issue by krisnaru** [jruere/multiprocessing-logging#22]
Log statement:
            num_alerts = len(self.__alerts)
            logger.info(
                "Writing {} messages to alerts topic".format(num_alerts))

Line:
https://github.com/jruere/multiprocessing-logging/blob/0120a138abf70989e589b3897c790f56c090224c/multiprocessing_logging.py#L86

Exception:
Traceback (most recent call last): File "/opt/company/jarvis/logger_config/multiprocess_logger.py", line 86, in emit s = self._format_record(record) File "/opt/company/jarvis/logger_config/multiprocess_logger.py", line 43, in _format_record record.msg = record.msg % record.args TypeError: not all arguments converted during string formatting

**Comment by jruere** [comment]
What is the actual string logged?

**Comment by krisnaru** [comment]
logger.info("Writing {} messages to alerts topic".format(num_alerts))
is throwing error.

**Comment by jruere** [comment]
Yes, I understand. When it fails, what is the value of `"Writing {} messages to alerts topic".format(num_alerts)`?

**Comment by jruere** [comment]
Or, what is the value of `num_alerts` when it fails?

**Comment by jruere** [comment]
The I don't understand how this could happen. Could you provide a small program that reproduces this problem?

**Comment by jruere** [comment]
Sorry, I cannot reproduce. Please, reopen if you can send a minimal example showing the problem.
