### ISSUE TITLE
Log entries only at the end

### ISSUE THREAD

**Issue by rgruebel** [jruere/multiprocessing-logging#23]
My log entries are only written to the text file when my program is finished. Am I doing something wrong or is that normal?

**Comment by oPromessa** [comment]
@rgruebel what OS are you using? Windows, Mac or some flavor of Linux?

**Comment by jruere** [comment]
Also Python version, please.

**Comment by rgruebel** [comment]
Python 3.7.2 on Windows 10

**Comment by jruere** [comment]
I don't support Windows but maybe other users will be able to help you.

**Comment by samypr100** [comment]
Maybe it's worth to be explicit about `os.fork` requirement due to the usage of `multiprocessing.Queue` in an expected fork-like behaviour?

Using `multiprocessing.set_start_method("spawn")` on linux/osx allows reproduction of some of the issues encountered on the issues here on windows even if you're on linux/osx.

**Comment by jruere** [comment]
But it reportedly works on Windows, no?

Furthermore, `multiprocessing.Queue` does not work with the "spawn" method? This is surprising to me. I expect all of multiprocessing to continue working with all methods. Am I mistaken?

**Comment by jruere** [comment]
@rgruebel if you could post a minimal program which shows the problem, it would help a lot.

**Comment by deajan** [comment]
If this happens to still be an issue, just for you to know, I use multiprocessing_logging under windows 10 with Python 3.7.6 and my logs appear in time before the program ends.
Willing to help if requested.

**Comment by jruere** [comment]
@deajan if you could explain how this actually works in Windows, it would be great!

**Comment by jruere** [comment]
I'll close this since Windows is now not supported for real. Thanks everyone who tried to help!
