### ISSUE TITLE
Provide PyPI project description

### ISSUE THREAD

**Issue by johnthagen** [jruere/multiprocessing-logging#25]
https://pypi.org/project/multiprocessing-logging/

> The author of this package has not provided a project description

**Comment by jruere** [comment]
That would be super nice but I don't know how to do it. If you could send a PR, I'd appreciate it!

**Comment by johnthagen** [comment]
You can do something like this: https://github.com/johnthagen/python-blueprint/blob/master/setup.py#L10

And: https://github.com/johnthagen/python-blueprint/blob/master/MANIFEST.in#L1

**Comment by jruere** [comment]
Thanks!

**Comment by jruere** [comment]
Done!
