### ISSUE TITLE
Causes Deadlock

### ISSUE THREAD

**Issue by bmccord2** [jruere/multiprocessing-logging#26]
I believe this is causing a deadlock in my project.   Currently I have certain processes which will unexpectedly stop mid-processing with no exceptions, this problem goes away when I disable multiprocessing-logging.  From what I have read it may be related to the GIL.   Here is a relevant discussion I have found, regarding this: https://bugs.python.org/issue27422

I have noticed many people warning not to mix threading and processes, or if you do to thread after you fork.  I am not well equipped to debug this any further than I have but I thought I would leave an issue here in case someone else has similar issues.

**Comment by jruere** [comment]
Yep, that is a fundamental problem. I'll see what I can do. If you want to give it a go, please do send a PR.

**Comment by jruere** [comment]
I don't see a way around this.

The Logger must be created before the fork but the thread should be created afterwards.
How can the Logger know if there will be no more forks?
How can the Logger know if the fork already took place?

**Comment by jruere** [comment]
I don't think there's a solution for this.
