### ISSUE TITLE
Does not work at all for subprocesses 

### ISSUE THREAD

**Issue by CMTaylor** [jruere/multiprocessing-logging#28]
I'm trying to use this multiprocessing-logging in Python 2.7.14 (32-bit) on Windows 10 (64-bit). It doesn't seem to work at all for the subprocesses. Looking at your code, I don't see how it could work, not just on Windows but anywhere! 

If you call `multiprocessing_logging.install_mp_handler()` inside `if __name__ == '__main__':` then only the first main process will know about the re-mapped logging, and only it will run the Queue receiver thread. If you call `multiprocessing_logging.install_mp_handler()` outside of `if __name__ == '__main__':` then then, from my reading of your code, every sub-process will know about the re-mapped logging, but every sub-process will also have a receiver thread running. This seems fundamentally incorrect and I cannot understand how it could work anywhere. Since you claim it works on Linux and Windows, there's obviously something that I'm not understanding about your implementation and how to use it.

I've attached my very simple test program as mp_exp.py.txt (since GitHub didn't support a .py file type) and the resulting log file for running this program with an arg of 10.

[mp_exp.py.txt](https://github.com/jruere/multiprocessing-logging/files/3693155/mp_exp.py.txt)
[mp_exp.log](https://github.com/jruere/multiprocessing-logging/files/3693156/mp_exp.log)

If I've made some stupid mistake in how I'm using this, please help me fix it.

**Comment by CMTaylor** [comment]
If I move the `multiprocessing_logging.install_mp_handler()` call outside the `if __name__ == '__main__':` (right after all the imports) then this is what I get in the log file.
[mp_exp.log](https://github.com/jruere/multiprocessing-logging/files/3693171/mp_exp.log)

Obviously garbled due to multiple processes trying to write to it at the same time.

**Comment by jruere** [comment]
I can only say that your code sends correct to me. 

I never understood how this module could work if the system is creating new processes by something else than `fork`.

**Comment by bo-naoki-okamoto** [comment]
I had been struggled with the same problem and finally figured out.
This doesn't work on Windows.
It perfectly worked for me when I changed to Linux.

**Comment by jruere** [comment]
Yep, makes perfect sense to me. Feedback from Windows users prompted me to add Windows but I never understood how it could work.
I'll add a reference from https://github.com/jruere/multiprocessing-logging/issues/9 here for other users to comment.

**Comment by Drau** [comment]
@CMTaylor, it makes sense that this is the behaviour you see on windows. 

On Windows the default multiprocessing start_method is `spawn`, which means almost no data is shared between processes. ( Including the new handler added to the logger ) 
On the other hand, Unix's default start_method is `fork`, which shares much more data between processes.

In your case, you run `multiprocessing_logging.install_mp_handler() `in the main process, but all other child processes created dont have this new handler in memory as they dont inherit it from the main process. 

#9 works as it calls `multiprocessing_logging.install_mp_handler` for all Pool processes initializer method. This will fail on a heavy load scenario where multiple processes will write to the same fd.
Im unsure as to how make this package work on windows. Its suitable for Unix systems.

**Comment by ericmclachlan** [comment]
That's a pity. 

If that's the case, could I ask you to update the README.md, which currently says,
> It was tested by users and reported to work on Windows with Python 3.5 and 3.6.

**Comment by jruere** [comment]
Updates README mentioning that Windows is not supported.
