### ISSUE TITLE
Why using a Queue rather than a simple Lock?

### ISSUE THREAD

**Issue by Delgan** [jruere/multiprocessing-logging#30]
Hi. :)

I have a quick question regarding the implementation of `MultiProcessingHandler`: why did you choose to rely on `multiprocessing.Queue()` rather than using a `multiprocessing.Lock()`?

This is basically a duplicate of this StackOverflow question: [Multiprocessing logging: Lock vs Queue](https://stackoverflow.com/questions/21419323/multiprocessing-logging-lock-vs-queue/21444348)

There is many discussions about `multiprocessing` and `logging` in Python, most of them suggest to use `multiprocessing.Queue()` alongside a thread for the receiving loop. This looks like a complicated implementation compared to simply wrapping the `emit()` calls with a lock.
I see that there is advantages, as it allows non-blocking handler. But this is about "multiprocessing logging", not "non-blocking logging", right? Others handlers are blocking by default anyway.

I wanted to know you opinion, what are the rational behind this choice?

**Comment by jruere** [comment]
That post describes the problem quite well.

IMO a queue has better properties than a lock for this use case:
* Preserves record order better
* Does not block all processes from logging at the same time
* Only one process has access to the file
* Works with any handler (eg. time based rotating handlers will rotate once)

The costs of this approach are:
* More memory usage (records are buffered)
* More IPC overhead (CPU)
* One process has an extra thread

There is one massive limitation: only works with fork.

If you implement an alternative library using locking, it would be interesting to see how it works in practice.

**Comment by Delgan** [comment]
Thanks @jruere for taking time to answering me!

Yeah, I agree that using a `Queue` is offers several benefits. I just wondered why it was the most common implementation while using a simple `Lock` seems easier. 

However, as you said, using a `Lock` would not work on Windows as it would require the file or stream object to be passed to the child process. This is complicated, as such objects are not serializable. So, it looks using locking is actually impracticable. :slightly_smiling_face: 

Thanks again! :+1:

**Comment by jruere** [comment]
I don't know if it's impractical.

It would need to be a specialised Handler, probably. I don't know file
locking on Windows so I cannot say.

**Comment by Delgan** [comment]
Maybe not "impractical", but definitely harder to use for the reasons you previously evoked: it would require multiple process to manage the same file. As a "file object" cannot be easily serialized, it cannot be shared with the child process. It would need to be re-opened, knowing the path. The same problem occurs with `sys.stderr` and all sort of handlers. So, this would need one specialized handler for each possible type... However, child process can inherit from `Queue` on Windows with no error, so using a `Queue` means it's compatible with all types of handlers.
