### ISSUE TITLE
Question on integration with libraries

### ISSUE THREAD

**Issue by RenzoTale88** [jruere/multiprocessing-logging#38]
Good morning,
I got a question on how to integrate the package in a python package I'm currently working on.
The package is structured as follow:
```
./bin/main.py
./src/lib/programs.py
./src/lib/workers.py
```
The access point to the software is ```main.py```, which also create the logger. Then, depending on the configuration, it passes the arguments to ```programs.py```, that runs the specific subprocesses of interest, described in ```worker.py```.

In worker, I got a situation as follow:
```
import logging
import subprocess as sp
import multiprocessing as mp
from multiprocessing_logging import install_mp_handler
logger = logging.getLogger(__name__)

# Initialiser for multiprocessing data
def init(args):
    ''' store the counter for later use '''
    global counter
    counter = args
    # Define parallel logging functions
    install_mp_handler()

# Counter object
class Counter(object):
    def __init__(self, initval=0):
        self.val = Value('i', initval)
        self.lock = Lock()
    def increment(self):
        with self.lock:
            self.val.value += 1            
    @property
    def value(self):
        return self.val.value

# Worker function.
def work( in_cmd ):
    global counter
    sp.call(in_cmd, shell=True)
    # += operation is not atomic, so we need to get a lock:
    counter.increment()
    if counter.value == 1:
        logger.info("Done {} job".format( counter.value ))
    else:
        logger.info("Done {} jobs".format( counter.value ))
    return 0


def runParallel(commands, threads):
    ncmds = len(commands)
    if threads > 1:
        # Define parallel counter
        counter = Counter(0)

        logger.info("Start jobs...")

        # Define parallel logging functions
        pool = mp.Pool(initializer = init, initargs = (counter, ), processes=threads)
        #Run the jobs
        pool.map(work, commands)
    else:
        for n, in_cmd in enumerate(commands):
            work( in_cmd )
            if n%10 == 0 and n>0: logger.info("Done {}".format(n))
    logging.info("Completed {} jobs.".format(ncmds))
    return None
```

Naively, I've tried to add the ```install_mp_handler()``` in the init function for the pool call. It didn't work, so i placed it as follow:
```
       install_mp_handler()
        # Define parallel logging functions
        pool = mp.Pool(initializer = init, initargs = (counter, ), processes=threads)
        #Run the jobs
        pool.map(work, commands)
        logger.info("Start jobs...")
```
But it didn't work either. So I've placed at the beginning of the software, in the ```main.py``` code, as below:
```
    import logging
    from multiprocessing_logging import install_mp_handler

    # Get arguments
    my_args = parser()

    # Define log format 
    LOGFORMAT = '%(asctime)s : %(levelname)s : %(message)s'
    logging.basicConfig(format=LOGFORMAT, level=my_args.verbose, datefmt="%Y-%m-%d %H:%M:%S")
    install_mp_handler()
```
But still it didn't work. I'm not sure what I am doing wrong, could you please give me some suggestion about it?
Thank you in advance
Andrea

**Comment by jruere** [comment]
Please provide OS & Python version.

Logging is usually configured in "main". The README has an example on how to do it.
Your last code snippet looks OK to me.

**Comment by RenzoTale88** [comment]
Sure, I'm using python 3.8.2 within an anaconda environment on macOS 10.15.5.

**Comment by jruere** [comment]
Starting with Python 3.8, the default method to create children is now `spawn` for macOS.
This library only works if the method is `fork`.

`fork` is considered [unsafe in macOS](https://bugs.python.org/issue33725).

I recommend that you don't use this library and instead configure logging to send to [syslog](https://docs.python.org/3/library/logging.handlers.html#sysloghandler), if it's present in macOS, or something similar.
