### ISSUE TITLE
conda-forge package

### ISSUE THREAD

**Issue by jordan-heemskerk** [jruere/multiprocessing-logging#39]
Hi @jruere 

Was wondering if you would consider creating a conda-forge package for multiprocessing-logging. Happy to collaborate on it if you'd like.

**Comment by jruere** [comment]
An alternative PyPI?! Just learned about it.
If you want to do it, go for it.

**Comment by jordan-heemskerk** [comment]
Started here: https://github.com/conda-forge/staged-recipes/pull/12092

**Comment by jruere** [comment]
I suppose this is done.
