### ISSUE TITLE
uninstall_mp_handler() doesn't handle >1 handlers

### ISSUE THREAD

**Issue by knightofni-i** [jruere/multiprocessing-logging#42]
Need to use 
`for handler in list(logger.handlers):`
instead of current
`for handler in logger.handlers:`
When I get some time, I will fork project and make a pull request.

**Comment by knightofni-i** [comment]
Additionally, we should call `self.manager.shutdown()` in `MultiProcessingHandler.close()`

**Comment by jruere** [comment]
This was contributed and has no tests. I'll work on it eventually.
Alternatively, if you want, you can submit a PR with tests and the fix.

**Comment by jruere** [comment]
This was fixed without tests. Will be released on the next version.
