### ISSUE TITLE
How to use this module

### ISSUE THREAD

**Issue by feldsam** [jruere/multiprocessing-logging#46]
Hi, I try to use this module according to the readme, but the logs seem to be messed like when I don't use this module. What I am doing wrong? 

```
import logging
from multiprocessing import Pool
from multiprocessing_logging import install_mp_handler
import functions
import globals as g

# init logging
logging.basicConfig(format='%(asctime)s - %(levelname)s - %(message)s', level=logging.INFO)
install_mp_handler()

# init multi processing pool
pool = Pool(g.args.parallel)

results = pool.map(functions.backup_image, [image for key, image in sorted(g.images.iteritems())])

pool.close()
```

and in `functions.backup_image` I use:

```
logging.info('Backup persistent image %d:%s attached to VM %d:%s as disk %d' % (
                image.ID, image.NAME, vmId, vm.NAME, vmDiskId))
```

**Comment by jruere** [comment]
Which OS and Python version are you using?

**Comment by feldsam** [comment]
OL7.9 and python 2.7.5

**Comment by jruere** [comment]
What is OL7.9?

**Comment by feldsam** [comment]
Oracle Linux 7.9, same as CentOS 7.9 or REHL 7.9

**Comment by jruere** [comment]
That's it. It should work. If you add a sleep after the `close()`, does it make a difference?

**Comment by feldsam** [comment]
Hi, nothing changed. I also try log to file, but logs are mixed too

**Comment by jruere** [comment]
No idea.

**Comment by feldsam** [comment]
probably problem of python 2.7? should I try python 3?

**Comment by jruere** [comment]
This module should work with either. If you can choose, I'd encourage you to always use Python 3.

**Comment by jruere** [comment]
Sorry, no idea what to do here. :(
