### ISSUE TITLE
Can you release new version to PyPi?

### ISSUE THREAD

**Issue by maiiku** [jruere/multiprocessing-logging#53]
Hello, 

It seems you merged a fix for lack of BrokenPipeError exception missing in python 2 on Dec of 2020, but you never released it to pypi - it seems the last version there is 3.1 from April that year.

Could you bump the version to 3.2 and release it to pypi?

Thanks!

**Comment by jruere** [comment]
I don't remember why I didn't release that change. I probably didn't like something so I should review.
I'll try to review this weekend and release.

**Comment by jruere** [comment]
Done!

**Comment by jruere** [comment]
@maiiku I removed that "fix" as it was just dead code, AFAICS. See commits for an explanation.

If you can help me reproduce the problem, I'll add a fix.

Nevertheless v0.3.2 was released with that "fix" and v0.3.3 without.
