### ISSUE TITLE
Concrete example?

### ISSUE THREAD

**Issue by git-n-pissed** [jruere/multiprocessing-logging#66]
I would love to see a concrete example of how this module is intended to be used.  Tried to understand by looking at the test cases, but I think I'm missing something.  Based on the comments on original SO question, I think it could be helpful to myself and others.

**Comment by jruere** [comment]
The README has this, no?

**Comment by git-n-pissed** [comment]
> The README has this, no?

I was looking for an MRE/SSCCE example which showed all the steps required to use this module.  The README is clear that `install_mp_handler` has to be called, but doesn't actually show anything being logged.  In my attempts thus far, I've been unsuccessful at getting this module to work correctly (integrating it into an existing proprietary logging module), so having an MRE/SSCCE example would help me narrow down what I'm doing wrong.

**Comment by git-n-pissed** [comment]
I was able to determine what I was doing wrong by looking more closely at the test file.
