### ISSUE TITLE
Only logging from one thread

### ISSUE THREAD

**Issue by gabeorlanski** [jruere/multiprocessing-logging#7]
Hello, I only one thread writing to the log file, is there any way to fix it?

**Comment by jruere** [comment]
If you are using threads, you don't need this library. Logging handles
synchronization.

If you meant processes, I can only guess, since you provide very little
information.

Did you fork before initializing the library?

**Comment by gabeorlanski** [comment]
I downloaded a zip version then installed it. I then ran the two lines of code you said too. I am using the multiprocessing module. It appears now that no logging is happening from inside of the processes. I am using a custom logging config through yaml.  If it makes a difference

**Comment by gabeorlanski** [comment]
I am on windows if it makes a difference

**Comment by jruere** [comment]
I have never tested this on Windows. It relies on the POSIX semantics of
fork.

Windows is probably different. I don't think it would work and I cannot
test it since I don't use it.

**Comment by jruere** [comment]
Added comment on the README about Windows not being supported.
