### ISSUE TITLE
logging working with pool on windows !

### ISSUE THREAD

**Issue by wavemaking** [jruere/multiprocessing-logging#9]
At present I'm using your pypi package on windows using a pool. When sending the install_handler function to the pool as intializer, I do not see any problems. Logging simply works, also from the child processes. Just wanted to let you know!

```
import logging
import multiprocessing

logger = logging.getLogger(__name__)
import multiprocessing_logging

[...]

pool = multiprocessing.Pool(processes=8, maxtasksperchild=20,  
initializer=multiprocessing_logging.install_mp_handler )

[...]
```

**Comment by jruere** [comment]
That's great news. How did you test it?

**Comment by wavemaking** [comment]
Well, I simply tried the method and noticed that I get log messages on the console and log file as configured from the main process!

**Comment by jruere** [comment]
That may not be quite enough to know it works. If you try logging without the module, doesn't it also log correctly?

You need to log very aggressively from all processes to notice a problem in a short test.

**Comment by wavemaking** [comment]
Well, without the module, log messages from the child processes do not arrive to the main logger. So that is the part that works and is a big improvement over not using your package. However, I did not try logging agressively and checked whether I have problems occuring. In my current applications I have 6 child processes (i could run with a few more) and about 2 log messages per second. At least it runs without exceptions. 

If you have a more thorough test case then I am glad to run that in my environment.

**Comment by leoschet** [comment]
any news on this?!

**Comment by mmngreco** [comment]
I just installed the project from PyPi and tested it directly in my test case (using pytest with xdist) and it seems to work perfectly in windows, I didn't see any problems in log file. I'll leave you the code below in case it's helpful.

__test_script.py__

```python
import time
import logging
import pytest
import multiprocessing_logging

logging.basicConfig(filename='test.log', level=logging.INFO, format='%(levelname)s:%(asctime)s:%(name)s:%(message)s')
multiprocessing_logging.install_mp_handler()

a_list = [1,2,3,4,5,6] * 1000

@pytest.mark.parametrize("a", a_list)
def test(a):
    time.sleep(0.01)
    stmt = a % 2
    logging.info(f"a={a},stmt={stmt}")
    assert stmt == 0, "Not even"
```

Then I run from bash:
```bash
$ pytest test_script.py -n6`
```

**Comment by jruere** [comment]
I'm not familiar with the workings of pytest. Does a regular forking script work?

Also, I cannot support Windows as I don't use it. If someone volunteers to keep it working, please send a pull request updating the README about Windows.

**Comment by oPromessa** [comment]
@mmngreco What python version are you using in Windows? 2.7 or 3.6?

**Comment by mmngreco** [comment]
@oPromessa I tested on python 3.6 and 3.5.

**Comment by jruere** [comment]
Updated README on commit https://github.com/jruere/multiprocessing-logging/commit/7eb87e3b89c1ffc0ec36365b032d7b6a2c2a6289

**Comment by zhejunliux** [comment]
> I'm not familiar with the workings of pytest. Does a regular forking script work?
> 
> Also, I cannot support Windows as I don't use it. If someone volunteers to keep it working, please send a pull request updating the README about Windows.

The above code did not undergo fork testing, I will forking test and out report.
